# Generated by Django 4.2.25 on 2025-10-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
