# Generated by Django 4.2.25 on 2025-10-28 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('counselor', 'counselor'), ('manager', 'Manager')], default='support', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('work_college', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('centre', models.CharField(choices=[('jalandhar1', 'Jalandhar 1'), ('jalandhar2', 'Jalandhar 2'), ('maqsudan', 'Maqsudan'), ('ludhiana', 'Ludhiana'), ('hoshiarpur', 'Hoshiarpur'), ('mohali', 'Mohali'), ('phagwara', 'Phagwara')], max_length=20)),
                ('batch_time', models.CharField(blank=True, max_length=50)),
                ('course_fee_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_interested', models.CharField(blank=True, max_length=100)),
                ('trade', models.CharField(choices=[('computer', 'Computer'), ('it', 'IT'), ('graphic_designing', 'Graphic Designing'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('ielts', 'IELTS'), ('ece', 'ECE'), ('programming', 'Programming'), ('digital_marketing', 'Digital Marketing'), ('hardware', 'Hardware'), ('networking', 'Networking')], max_length=20)),
                ('enquiry_source', models.CharField(choices=[('social_media', 'Social Media'), ('just_dial', 'Just Dial'), ('random_call', 'Random Call'), ('direct_visit', 'Direct Visit'), ('banner', 'Banner'), ('website', 'Website'), ('reference', 'Reference'), ('newspaper', 'Newspaper'), ('friend_reference', 'Friend Reference'), ('google_search', 'Google Search')], max_length=20)),
                ('enquiry_status', models.CharField(choices=[('registration_done', 'Registration Done'), ('visited', 'Visited'), ('in_process', 'In Process'), ('negative', 'Negative'), ('positive', 'Positive'), ('follow_up_required', 'Follow Up Required'), ('admission_done', 'Admission Done'), ('course_completed', 'Course Completed'), ('dropped', 'Dropped')], default='new', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_enquiries', to='staff_app.staffprofile')),
                ('enquiry_taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_taken', to='staff_app.staffprofile')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
