# Generated by Django 4.2.25 on 2025-10-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('software_covered', models.TextField(blank=True)),
                ('duration_months', models.CharField(choices=[('6_weeks', '6 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('4_months', '4 Months'), ('5_months', '5 Months'), ('6_months', '6 Months'), ('7_months', '7 Months'), ('8_months', '8 Months'), ('9_months', '9 Months'), ('10_months', '10 Months'), ('1_year', '1 Year')], max_length=20)),
                ('duration_hours', models.IntegerField(help_text='Total course hours')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['course_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_types',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('jalandhar1', 'Jalandhar 1'), ('jalandhar2', 'Jalandhar 2'), ('maqsudan', 'Maqsudan'), ('ludhiana', 'Ludhiana'), ('hoshiarpur', 'Hoshiarpur'), ('mohali', 'Mohali'), ('phagwara', 'Phagwara')], max_length=20)),
                ('joining_date', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('work_college', models.CharField(max_length=100)),
                ('contact_address', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15)),
                ('parents_no', models.CharField(blank=True, max_length=15)),
                ('software_covered', models.TextField(blank=True)),
                ('duration_months', models.CharField(choices=[('6_weeks', '6 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('4_months', '4 Months'), ('5_months', '5 Months'), ('6_months', '6 Months'), ('7_months', '7 Months'), ('8_months', '8 Months'), ('9_months', '9 Months'), ('10_months', '10 Months'), ('1_year', '1 Year')], max_length=20)),
                ('duration_hours', models.IntegerField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='staff_app.course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='staff_app.coursetype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='staff_app.staffprofile')),
            ],
            options={
                'db_table': 'student_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='staff_app.coursetype'),
        ),
    ]
