# Generated by Django 4.2.25 on 2025-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_course_coursetype_studentregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
