# Generated by Django 4.2.25 on 2025-10-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0004_studentregistration_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='course_fee',
        ),
    ]
