# Generated by Django 4.2.25 on 2025-10-29 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0005_remove_studentregistration_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
