# Generated by Django 4.2.25 on 2025-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0006_alter_studentregistration_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
