# Generated by Django 4.2.25 on 2025-10-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0007_alter_studentregistration_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Installment number (1st, 2nd, 3rd, etc.)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID for online payments', max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='staff_app.staffprofile')),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='staff_app.studentregistration')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['installment_number'],
            },
        ),
    ]
